name: Build and Deploy Docker Image

on:
  workflow_run:
    workflows: ["Run Tests"]  # Nom du workflow de tests
    types:
      - completed  # Ce workflow se déclenche quand le workflow de tests est terminé

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success'   
    
    steps:
      - name: Checkout code (with full history and tags)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Extract git tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --exact-match || echo "")
          echo "Found tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: vincentgimenes123/gemini_chat_app
          tags: |
            type=raw,value=${{ steps.get_tag.outputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            API_KEY_GOOGLE=${{ secrets.API_KEY_GOOGLE }}
            FIREBASE_CONFIG_B64=${{ secrets.FIREBASE_CONFIG_B64 }}
