name: Lint & Typing Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-typing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [linting, typing]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy flake8 black

      - name: Run flake8 (linting)
        if: matrix.task == 'linting'
        run: flake8 .

      - name: Run black (formatting check)
        if: matrix.task == 'linting'
        run: black --check .

      - name: Run mypy (typing check)
        if: matrix.task == 'typing'
        run: mypy app/
