name: Run Tests

on:
  push:
    branches: [main]
    paths:
      - "app/**/*.py"
  pull_request:
    branches: [main]
    paths:
      - "app/**/*.py"       # activation uniquement en cas de changement des *.py

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests with pytest
        working-directory: app
        run: pytest --maxfail=3 --disable-warnings
        
